excludes:
  paths:
  - pattern: "**/src/{:funTest|test}/**"
    reason: "TEST_OF"
    comment: >-
      Licenses contained in this directory are used for testing and do not apply to the ORT server.
  scopes:
  - pattern: ".*[tT]est.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: >-
      Packages for testing only. Not part of released artifacts.
  - pattern: "detekt.*"
    reason: "DEV_DEPENDENCY_OF"
    comment: >-
      Packages for static code analysis.
