# Copyright (C) 2022 The ORT Project Authors (See <https://github.com/oss-review-toolkit/ort-server/blob/main/NOTICE>)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

[versions]
# Docker
# When updating this version make sure to keep it in sync with the worker Dockerfiles.
eclipseTemurin = "17.0.7_7-jdk-jammy@sha256:d3b5da78625955ac2ce903df64bfba33e7d788b67b3eb28275b808f71d2ec922"

# Gradle plugins
dependencyAnalysisPlugin = "1.20.0"
detektPlugin = "1.23.0"
jibPlugin = "3.3.2"
kotlinPlugin = "1.9.10"
kotlinxCoroutines = "1.7.3"
kotlinxDatetime = "0.4.1"
kotlinxSerialization = "1.6.0"
rabbitMq = "5.18.0"
versionCatalogUpdatePlugin = "0.8.0"
versionsPlugin = "0.47.0"

# Gradle dependencies
exposed = "0.44.0"
flyway = "9.22.2"
hikari = "5.0.1"
jackson = "2.15.2"
jsonSchemaSerialization = "0.6.6"
kaml = "0.55.0"
keycloakTestcontainerVersion = "2.5.0"
koin = "3.5.0"
koinKtor = "3.5.1"
koinTest = "3.5.0"
konform = "0.4.0"
kotest = "5.7.2"
kotestAssertionsKotlinxDatetime = "1.1.0"
kotestAssertionsKtor = "2.0.0"
kotestExtensionTestContainers = "2.0.2"
ktor = "2.3.5"
ktorSwaggerUi = "2.5.0"
kubernetesClient = "18.0.0"
log4j = "2.20.0"
logback = "1.4.8"
micrometer = "1.11.2"
mockk = "1.13.5"
ort = "7250e669b0"
postgres = "42.6.0"
qpidJmsClient = "2.3.0"
slf4j = "2.0.7"
testContainers = "1.19.1"
typesafeConfig = "1.4.2"
wiremock = "2.35.0"

[plugins]
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysisPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jibPlugin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinPlugin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[libraries]
exposedCore = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposedDao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposedJdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposedJson = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposedKotlinDatetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
flywayCore = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
jacksonModuleKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jsonSchemaSerialization = { module = "com.github.Ricky12Awesome:json-schema-serialization", version.ref = "jsonSchemaSerialization" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinKtor = { module = "io.insert-koin:koin-ktor", version.ref = "koinKtor" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
konform = { module = "io.konform:konform", version.ref = "konform" }
kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestAssertionsKotlinxDatetime = { module = "io.kotest.extensions:kotest-assertions-kotlinx-datetime", version.ref = "kotestAssertionsKotlinxDatetime" }
kotestAssertionsKtor = { module = "io.kotest.extensions:kotest-assertions-ktor", version.ref = "kotestAssertionsKtor" }
kotestExtensionsTestContainer = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version.ref = "kotestExtensionTestContainers" }
kotestFrameworkApi = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotestRunnerJunit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktorClientAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorHttp = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktorKotlinxSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktorServerAuth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktorServerAuthJwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktorServerCallLogging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktorServerCommon = { module = "io.ktor:ktor-server-host-common-jvm", version.ref = "ktor" }
ktorServerContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerDefaultHeaders = { module = "io.ktor:ktor-server-default-headers-jvm", version.ref = "ktor" }
ktorServerMetricsMicrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
ktorServerNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktor" }
ktorServerTestHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktorServerTestsJvm = { module = "io.ktor:ktor-server-tests-jvm", version.ref = "ktor" }
ktorSwaggerUi = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktorSwaggerUi" }
ktorValidation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
kubernetesClient = { module = "io.kubernetes:client-java", version.ref = "kubernetesClient" }
kubernetesClientExtended = { module = "io.kubernetes:client-java-extended", version.ref = "kubernetesClient" }
log4jToSlf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micrometerRegistryGraphite = { module = "io.micrometer:micrometer-registry-graphite", version.ref = "micrometer" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
ortAdvisor = { module = "com.github.oss-review-toolkit.ort:advisor", version.ref = "ort" }
ortAnalyzer = { module = "com.github.oss-review-toolkit.ort:analyzer", version.ref = "ort" }
ortDownloader = { module = "com.github.oss-review-toolkit.ort:downloader", version.ref = "ort" }
ortEvaluator = { module = "com.github.oss-review-toolkit.ort:evaluator", version.ref = "ort" }
ortModel = { module = "com.github.oss-review-toolkit.ort:model", version.ref = "ort" }
ortPackageConfigurationProviders = { module = "com.github.oss-review-toolkit.ort:package-configuration-providers", version.ref = "ort" }
ortPackageCurationProviders = { module = "com.github.oss-review-toolkit.ort:package-curation-providers", version.ref = "ort" }
ortPackageManagers = { module = "com.github.oss-review-toolkit.ort:package-managers", version.ref = "ort" }
ortReporter = { module = "com.github.oss-review-toolkit.ort:reporter", version.ref = "ort" }
ortReporters = { module = "com.github.oss-review-toolkit.ort:reporters", version.ref = "ort" }
ortScanner = { module = "com.github.oss-review-toolkit.ort:scanner", version.ref = "ort" }
ortScanners = { module = "com.github.oss-review-toolkit.ort:scanners", version.ref = "ort" }
ortScriptingUtils = { module = "com.github.oss-review-toolkit.ort:scripting-utils", version.ref = "ort" }
ortTestUtils = { module = "com.github.oss-review-toolkit.ort:test-utils", version.ref = "ort" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
qpidJmsClient = { module = "org.apache.qpid:qpid-jms-client", version.ref = "qpidJmsClient" }
rabbitMqAmqpClient = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitMq" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testContainers = { module = "org.testcontainers:testcontainers", version.ref = "testContainers" }
testContainersKeycloak = { module = "com.github.dasniko:testcontainers-keycloak", version.ref = "keycloakTestcontainerVersion" }
testContainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testContainers" }
testContainersRabbitMq = { module = "org.testcontainers:rabbitmq", version.ref = "testContainers" }
testContainersVault = { module = "org.testcontainers:vault", version.ref = "testContainers" }
typesafeConfig = { module = "com.typesafe:config", version.ref = "typesafeConfig" }
wiremockStandalone = { module = "com.github.tomakehurst:wiremock-jre8-standalone", version.ref = "wiremock" }
