name: Build and Test

on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Build all classes
      uses: gradle/gradle-build-action@v3
      with:
        gradle-home-cache-cleanup: true
        arguments: --stacktrace classes
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Run tests
      uses: gradle/gradle-build-action@v3
      with:
        gradle-home-cache-cleanup: true
        arguments:  test -Dkotest.tags='!Integration'
  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run tests
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true
          arguments: test -Dkotest.tags='Integration'
