name: Build and Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: Build all classes
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --stacktrace classes
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: Run tests
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: test
