name: Static Analysis

on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  commit-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml
  detekt-issues:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: Check for Detekt Issues
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --stacktrace detekt
  reuse-tool:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Check REUSE Compliance
      run: |
        pip3 install --user reuse==1.1.2
        pip3 install --user --force-reinstall python-debian==0.1.40 # See https://github.com/fsfe/reuse-tool/issues/427.
        ~/.local/bin/reuse lint
