name: Static Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  detekt-issues:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: Check for Detekt Issues
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: --stacktrace detekt
  reuse-tool:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Check REUSE Compliance
      run: |
        pip3 install --user reuse
        pip3 install --user --force-reinstall python-debian==0.1.40 # See https://github.com/fsfe/reuse-tool/issues/427.
        ~/.local/bin/reuse lint
